# Generated by Django 3.0.6 on 2020-06-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0004_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
