# Generated by Django 3.0.6 on 2020-06-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0007_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
