# Generated by Django 3.1.2 on 2020-10-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0015_remove_cart_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
