# Generated by Django 3.1.2 on 2020-10-08 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0017_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
